import '../l10n.dart';

/// One CLI lab: a task against the canned IOS device, with a multiple-choice check.
class LabDef {
  const LabDef({
    required this.id,
    required this.titlePt,
    required this.titleEn,
    required this.taskPt,
    required this.taskEn,
    required this.hint,
    required this.optionsPt,
    required this.optionsEn,
    required this.correct,
    required this.explainPt,
    required this.explainEn,
  });

  final String id;
  final String titlePt;
  final String titleEn;
  final String taskPt;
  final String taskEn;
  final String hint;
  final List<String> optionsPt;
  final List<String> optionsEn;
  final int correct;
  final String explainPt;
  final String explainEn;

  String title(S s) => s.isPt ? titlePt : titleEn;
  String task(S s) => s.isPt ? taskPt : taskEn;
  List<String> options(S s) => s.isPt ? optionsPt : optionsEn;
  String explain(S s) => s.isPt ? explainPt : explainEn;

  bool isCorrect(int? answer) => answer != null && answer == correct;
}

const List<LabDef> labCatalog = [
  LabDef(
    id: 'int-down',
    titlePt: 'Interface em baixo',
    titleEn: 'Interface down',
    taskPt:
        'Usa o terminal. Qual interface está down (não administratively down)?',
    taskEn: 'Use the terminal. Which interface is down (not administratively down)?',
    hint: 'show ip interface brief',
    optionsPt: [
      'GigabitEthernet0/0',
      'GigabitEthernet0/2',
      'Vlan1',
      'Loopback0',
    ],
    optionsEn: [
      'GigabitEthernet0/0',
      'GigabitEthernet0/2',
      'Vlan1',
      'Loopback0',
    ],
    correct: 1,
    explainPt: 'Gi0/2 aparece como down/down e unassigned. Vlan1 está administratively down.',
    explainEn:
        'Gi0/2 shows down/down and unassigned. Vlan1 is administratively down.',
  ),
  LabDef(
    id: 'vlan-admin',
    titlePt: 'VLAN encerrada',
    titleEn: 'Shutdown VLAN',
    taskPt: 'Qual SVI está administratively down?',
    taskEn: 'Which SVI is administratively down?',
    hint: 'show ip interface brief',
    optionsPt: ['Vlan10', 'Vlan20', 'Vlan1', 'GigabitEthernet0/2'],
    optionsEn: ['Vlan10', 'Vlan20', 'Vlan1', 'GigabitEthernet0/2'],
    correct: 2,
    explainPt: 'Vlan1 está "administratively down / down". Gi0/2 está só down.',
    explainEn: 'Vlan1 is "administratively down / down". Gi0/2 is just down.',
  ),
  LabDef(
    id: 'vlan-name',
    titlePt: 'Nome da VLAN 10',
    titleEn: 'VLAN 10 name',
    taskPt: 'Qual é o nome da VLAN 10?',
    taskEn: 'What is the name of VLAN 10?',
    hint: 'show vlan brief',
    optionsPt: ['default', 'ENG', 'SALES', 'GUEST'],
    optionsEn: ['default', 'ENG', 'SALES', 'GUEST'],
    correct: 2,
    explainPt: 'VLAN 10 chama-se SALES (portas Gi1/0/9-10).',
    explainEn: 'VLAN 10 is named SALES (ports Gi1/0/9-10).',
  ),
  LabDef(
    id: 'vlan-ports',
    titlePt: 'Portas da VLAN 20',
    titleEn: 'VLAN 20 ports',
    taskPt: 'Que VLAN contém Gi1/0/5 a Gi1/0/8?',
    taskEn: 'Which VLAN contains Gi1/0/5 through Gi1/0/8?',
    hint: 'show vlan brief',
    optionsPt: [
      'VLAN 1 default',
      'VLAN 10 SALES',
      'VLAN 20 ENG',
      'VLAN 99 MGMT',
    ],
    optionsEn: [
      'VLAN 1 default',
      'VLAN 10 SALES',
      'VLAN 20 ENG',
      'VLAN 99 MGMT',
    ],
    correct: 2,
    explainPt: 'VLAN 20 (ENG) tem Gi1/0/5, Gi1/0/6, Gi1/0/7 e Gi1/0/8.',
    explainEn: 'VLAN 20 (ENG) has Gi1/0/5, Gi1/0/6, Gi1/0/7 and Gi1/0/8.',
  ),
  LabDef(
    id: 'gateway',
    titlePt: 'Gateway of last resort',
    titleEn: 'Gateway of last resort',
    taskPt: 'Qual é o gateway of last resort?',
    taskEn: 'What is the gateway of last resort?',
    hint: 'show ip route',
    optionsPt: ['10.0.0.2', '192.168.1.1', '192.168.1.254', '1.1.1.1'],
    optionsEn: ['10.0.0.2', '192.168.1.1', '192.168.1.254', '1.1.1.1'],
    correct: 2,
    explainPt: 'A tabela mostra "Gateway of last resort is 192.168.1.254" (rota estática S*).',
    explainEn: 'The table shows "Gateway of last resort is 192.168.1.254" (static S*).',
  ),
  LabDef(
    id: 'etherchannel-proto',
    titlePt: 'Protocolo EtherChannel',
    titleEn: 'EtherChannel protocol',
    taskPt: 'Que protocolo agrega o Port-channel 1?',
    taskEn: 'Which protocol aggregates Port-channel 1?',
    hint: 'show etherchannel summary',
    optionsPt: ['PAgP', 'LACP', 'Static (on)', 'NONE'],
    optionsEn: ['PAgP', 'LACP', 'Static (on)', 'NONE'],
    correct: 1,
    explainPt: 'Po1(SU) usa LACP, com Gi1/0/1(P) e Gi1/0/2(P).',
    explainEn: 'Po1(SU) uses LACP, with Gi1/0/1(P) and Gi1/0/2(P).',
  ),
  LabDef(
    id: 'etherchannel-ports',
    titlePt: 'Membros do Po1',
    titleEn: 'Po1 members',
    taskPt: 'Quais portas estão bundled no Po1?',
    taskEn: 'Which ports are bundled in Po1?',
    hint: 'show etherchannel summary',
    optionsPt: [
      'Gi0/1 e Gi0/2',
      'Gi1/0/1 e Gi1/0/2',
      'Gi1/0/5 e Gi1/0/6',
      'Gi1/0/9 e Gi1/0/10',
    ],
    optionsEn: [
      'Gi0/1 and Gi0/2',
      'Gi1/0/1 and Gi1/0/2',
      'Gi1/0/5 and Gi1/0/6',
      'Gi1/0/9 and Gi1/0/10',
    ],
    correct: 1,
    explainPt: 'O resumo lista Gi1/0/1(P) e Gi1/0/2(P) no grupo 1.',
    explainEn: 'The summary lists Gi1/0/1(P) and Gi1/0/2(P) in group 1.',
  ),
  LabDef(
    id: 'cdp-nei',
    titlePt: 'Vizinho CDP',
    titleEn: 'CDP neighbor',
    taskPt: 'Que dispositivo está ligado a Gig 0/1?',
    taskEn: 'Which device is connected to Gig 0/1?',
    hint: 'show cdp neighbors',
    optionsPt: ['SW2.lab.local', 'AP1.lab.local', 'R1.lab.local', 'ISR4331'],
    optionsEn: ['SW2.lab.local', 'AP1.lab.local', 'R1.lab.local', 'ISR4331'],
    correct: 2,
    explainPt:
        'R1.lab.local aparece em Local Intrfce Gig 0/1 (plataforma ISR4331).',
    explainEn: 'R1.lab.local is on Local Intrfce Gig 0/1 (platform ISR4331).',
  ),
  LabDef(
    id: 'ospf-dr',
    titlePt: 'OSPF Designated Router',
    titleEn: 'OSPF Designated Router',
    taskPt: 'Qual é o Router ID do vizinho em estado FULL/DR?',
    taskEn: 'What is the Router ID of the neighbor in FULL/DR?',
    hint: 'show ip ospf neighbor',
    optionsPt: ['1.1.1.1', '2.2.2.2', '3.3.3.3', '10.0.0.2'],
    optionsEn: ['1.1.1.1', '2.2.2.2', '3.3.3.3', '10.0.0.2'],
    correct: 1,
    explainPt: '2.2.2.2 está FULL/DR em GigabitEthernet0/1; 3.3.3.3 é BDR.',
    explainEn: '2.2.2.2 is FULL/DR on GigabitEthernet0/1; 3.3.3.3 is BDR.',
  ),
  LabDef(
    id: 'bgp-idle',
    titlePt: 'Sessão BGP Idle',
    titleEn: 'Idle BGP session',
    taskPt: 'Que vizinho BGP está Idle?',
    taskEn: 'Which BGP neighbor is Idle?',
    hint: 'show ip bgp summary',
    optionsPt: ['10.0.0.2', '203.0.113.1', '192.0.2.8', '1.1.1.1'],
    optionsEn: ['10.0.0.2', '203.0.113.1', '192.0.2.8', '1.1.1.1'],
    correct: 2,
    explainPt: '192.0.2.8 (AS 65002) está Idle, Up/Down never, 0 prefixes.',
    explainEn: '192.0.2.8 (AS 65002) is Idle, Up/Down never, 0 prefixes.',
  ),
  LabDef(
    id: 'run-desc',
    titlePt: 'Descrição Gi0/0',
    titleEn: 'Gi0/0 description',
    taskPt: 'Qual é a description de GigabitEthernet0/0? (podes precisar de enable)',
    taskEn:
        'What is the description of GigabitEthernet0/0? (you may need enable)',
    hint: 'enable  →  show running-config',
    optionsPt: ['TO-R2', 'UNUSED', 'UPLINK-WAN', 'SALES'],
    optionsEn: ['TO-R2', 'UNUSED', 'UPLINK-WAN', 'SALES'],
    correct: 2,
    explainPt: 'show running-config (modo privilegiado) mostra "description UPLINK-WAN" em Gi0/0.',
    explainEn: 'show running-config (privileged EXEC) shows "description UPLINK-WAN" on Gi0/0.',
  ),
  LabDef(
    id: 'run-ospf',
    titlePt: 'Processo OSPF',
    titleEn: 'OSPF process',
    taskPt: 'Qual é o process ID OSPF no running-config?',
    taskEn: 'What is the OSPF process ID in the running-config?',
    hint: 'enable  →  show running-config',
    optionsPt: ['1', '10', '110', '65001'],
    optionsEn: ['1', '10', '110', '65001'],
    correct: 0,
    explainPt: 'A config tem "router ospf 1" com router-id 1.1.1.1.',
    explainEn: 'The config has "router ospf 1" with router-id 1.1.1.1.',
  ),

  // ---- New labs (show / config) ----
  LabDef(
    id: 'ospf-route-ia',
    titlePt: 'Rota OSPF inter-area',
    titleEn: 'OSPF inter-area route',
    taskPt: 'Qual prefixo aparece como O IA em show ip route ospf?',
    taskEn: 'Which prefix appears as O IA in show ip route ospf?',
    hint: 'show ip route ospf',
    optionsPt: ['10.2.2.0/24', '10.3.3.0/24', '0.0.0.0/0', '192.168.1.0/24'],
    optionsEn: ['10.2.2.0/24', '10.3.3.0/24', '0.0.0.0/0', '192.168.1.0/24'],
    correct: 1,
    explainPt: 'O IA 10.3.3.0/24 via 10.0.0.2; 10.2.2.0/24 é O (intra-area).',
    explainEn: 'O IA 10.3.3.0/24 via 10.0.0.2; 10.2.2.0/24 is O (intra-area).',
  ),
  LabDef(
    id: 'ospf-bdr',
    titlePt: 'OSPF Backup DR',
    titleEn: 'OSPF Backup DR',
    taskPt: 'Qual Neighbor ID está FULL/BDR?',
    taskEn: 'Which Neighbor ID is FULL/BDR?',
    hint: 'show ip ospf neighbor',
    optionsPt: ['1.1.1.1', '2.2.2.2', '3.3.3.3', '10.0.0.6'],
    optionsEn: ['1.1.1.1', '2.2.2.2', '3.3.3.3', '10.0.0.6'],
    correct: 2,
    explainPt: '3.3.3.3 está FULL/BDR em Gi0/3; 2.2.2.2 é o DR.',
    explainEn: '3.3.3.3 is FULL/BDR on Gi0/3; 2.2.2.2 is the DR.',
  ),
  LabDef(
    id: 'stp-root',
    titlePt: 'Root bridge STP VLAN 10',
    titleEn: 'STP root for VLAN 10',
    taskPt: 'Qual é o endereço MAC do Root ID em VLAN 10?',
    taskEn: 'What is the Root ID MAC address for VLAN 10?',
    hint: 'show spanning-tree vlan 10',
    optionsPt: [
      'aabb.cc00.0100',
      '0011.2233.4455',
      '0050.56c0.0001',
      '0063.6973.636f',
    ],
    optionsEn: [
      'aabb.cc00.0100',
      '0011.2233.4455',
      '0050.56c0.0001',
      '0063.6973.636f',
    ],
    correct: 1,
    explainPt: 'Root ID Address é 0011.2233.4455; aabb.cc00.0100 é o Bridge ID local.',
    explainEn: 'Root ID Address is 0011.2233.4455; aabb.cc00.0100 is the local Bridge ID.',
  ),
  LabDef(
    id: 'int-status-nc',
    titlePt: 'Porta notconnect',
    titleEn: 'notconnect port',
    taskPt: 'Qual porta aparece como notconnect em show interfaces status?',
    taskEn: 'Which port shows as notconnect in show interfaces status?',
    hint: 'show interfaces status',
    optionsPt: ['Gi1/0/5', 'Gi1/0/7', 'Gi1/0/9', 'Po1'],
    optionsEn: ['Gi1/0/5', 'Gi1/0/7', 'Gi1/0/9', 'Po1'],
    correct: 1,
    explainPt: 'Gi1/0/7 está notconnect na VLAN 20; as outras listadas estão connected.',
    explainEn: 'Gi1/0/7 is notconnect in VLAN 20; the other listed ports are connected.',
  ),
  LabDef(
    id: 'int-status-vlan',
    titlePt: 'VLAN da porta Gi1/0/9',
    titleEn: 'Gi1/0/9 access VLAN',
    taskPt: 'Em que VLAN está Gi1/0/9 (show interfaces status)?',
    taskEn: 'Which VLAN is Gi1/0/9 in (show interfaces status)?',
    hint: 'show interfaces status',
    optionsPt: ['1', '10', '20', 'trunk'],
    optionsEn: ['1', '10', '20', 'trunk'],
    correct: 1,
    explainPt: 'Gi1/0/9 está connected na VLAN 10 (SALES).',
    explainEn: 'Gi1/0/9 is connected in VLAN 10 (SALES).',
  ),
  LabDef(
    id: 'dhcp-binding',
    titlePt: 'Binding DHCP manual',
    titleEn: 'Manual DHCP binding',
    taskPt: 'Que IP tem lease Infinite (Manual) no DHCP binding?',
    taskEn: 'Which IP has an Infinite (Manual) lease in the DHCP binding?',
    hint: 'show ip dhcp binding',
    optionsPt: ['192.168.1.50', '10.10.10.25', '10.20.20.88', '203.0.113.10'],
    optionsEn: ['192.168.1.50', '10.10.10.25', '10.20.20.88', '203.0.113.10'],
    correct: 2,
    explainPt: '10.20.20.88 é Manual com expiração Infinite; os outros são Automatic.',
    explainEn: '10.20.20.88 is Manual with Infinite expiration; the others are Automatic.',
  ),
  LabDef(
    id: 'nat-xlate',
    titlePt: 'Tradução NAT estática',
    titleEn: 'Static NAT translation',
    taskPt: 'Qual Inside global corresponde a 10.20.20.88?',
    taskEn: 'Which Inside global maps to 10.20.20.88?',
    hint: 'show ip nat translations',
    optionsPt: ['203.0.113.10', '203.0.113.11', '198.51.100.8', '8.8.8.8'],
    optionsEn: ['203.0.113.10', '203.0.113.11', '198.51.100.8', '8.8.8.8'],
    correct: 1,
    explainPt: 'A linha estática --- 203.0.113.11 10.20.20.88 --- --- mapeia esse host.',
    explainEn: 'The static line --- 203.0.113.11 10.20.20.88 --- --- maps that host.',
  ),
  LabDef(
    id: 'acl-deny',
    titlePt: 'ACL 100 deny',
    titleEn: 'ACL 100 deny',
    taskPt: 'Que rede é negada pela linha 30 da ACL 100?',
    taskEn: 'Which network is denied by ACL 100 line 30?',
    hint: 'show access-lists',
    optionsPt: [
      '10.10.10.0/24',
      '10.20.20.0/24',
      '10.30.30.0/24',
      '192.168.1.0/24',
    ],
    optionsEn: [
      '10.10.10.0/24',
      '10.20.20.0/24',
      '10.30.30.0/24',
      '192.168.1.0/24',
    ],
    correct: 2,
    explainPt: 'Linha 30: deny ip 10.30.30.0 0.0.0.255 any.',
    explainEn: 'Line 30: deny ip 10.30.30.0 0.0.0.255 any.',
  ),
  LabDef(
    id: 'logging-trap',
    titlePt: 'Nível trap do syslog',
    titleEn: 'Syslog trap level',
    taskPt: 'Qual é o nível de Trap logging?',
    taskEn: 'What is the Trap logging level?',
    hint: 'show logging',
    optionsPt: ['debugging', 'informational', 'warnings', 'errors'],
    optionsEn: ['debugging', 'informational', 'warnings', 'errors'],
    correct: 2,
    explainPt: 'Trap logging: level warnings, facility local7 (para 192.168.1.100).',
    explainEn: 'Trap logging: level warnings, facility local7 (to 192.168.1.100).',
  ),
  LabDef(
    id: 'cfg-hostname',
    titlePt: 'Configurar hostname',
    titleEn: 'Configure hostname',
    taskPt:
        'Entra em enable → configure terminal, define hostname LAB-CORE, depois verifica com show run | include hostname. Qual hostname fica na config?',
    taskEn:
        'Enter enable → configure terminal, set hostname LAB-CORE, then verify with show run | include hostname. Which hostname is in the config?',
    hint: 'conf t → hostname LAB-CORE → end → show run | include hostname',
    optionsPt: ['SW1', 'LAB-CORE', 'R1', 'CORE-SW'],
    optionsEn: ['SW1', 'LAB-CORE', 'R1', 'CORE-SW'],
    correct: 1,
    explainPt: 'O comando hostname LAB-CORE altera o prompt e a linha hostname no running-config.',
    explainEn: 'The hostname LAB-CORE command changes the prompt and the hostname line in running-config.',
  ),
  LabDef(
    id: 'cfg-int-up',
    titlePt: 'Ativar Gi0/2 com IP',
    titleEn: 'Bring up Gi0/2 with IP',
    taskPt:
        'Em conf t: interface Gi0/2, ip address 172.16.0.1 255.255.255.0, no shutdown. Depois show run | include 172.16.0.1 — que IP configuraste?',
    taskEn:
        'In conf t: interface Gi0/2, ip address 172.16.0.1 255.255.255.0, no shutdown. Then show run | include 172.16.0.1 — which IP did you set?',
    hint: 'int Gi0/2 → ip address 172.16.0.1 255.255.255.0 → no shut',
    optionsPt: ['10.0.0.1', '172.16.0.1', '192.168.1.1', '172.16.10.1'],
    optionsEn: ['10.0.0.1', '172.16.0.1', '192.168.1.1', '172.16.10.1'],
    correct: 1,
    explainPt: 'Gi0/2 passa a ter 172.16.0.1/24 e no shutdown no running-config.',
    explainEn: 'Gi0/2 now has 172.16.0.1/24 and no shutdown in running-config.',
  ),
  LabDef(
    id: 'cfg-ospf-net',
    titlePt: 'Network statement OSPF',
    titleEn: 'OSPF network statement',
    taskPt:
        'Em conf t → router ospf 1, adiciona: network 10.20.20.0 0.0.0.255 area 0. Verifica com show run | include 10.20.20. Qual wildcard usaste?',
    taskEn:
        'In conf t → router ospf 1, add: network 10.20.20.0 0.0.0.255 area 0. Verify with show run | include 10.20.20. Which wildcard did you use?',
    hint: 'router ospf 1 → network 10.20.20.0 0.0.0.255 area 0',
    optionsPt: ['0.0.0.0', '0.0.0.3', '0.0.0.255', '255.255.255.0'],
    optionsEn: ['0.0.0.0', '0.0.0.3', '0.0.0.255', '255.255.255.0'],
    correct: 2,
    explainPt: 'Wildcard 0.0.0.255 cobre a rede /24 10.20.20.0 na area 0.',
    explainEn: 'Wildcard 0.0.0.255 covers the /24 network 10.20.20.0 in area 0.',
  ),
];
